---
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp-lb
  namespace: pihole
spec:
  ports:
    - port: 53
      protocol: TCP
      targetPort: 53
      name: dns-port
    - port: 8080
      protocol: TCP
      targetPort: 80
      name: web-port
  selector:
    app: pihole
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp-lb
  namespace: pihole
spec:
  ports:
    - port: 53
      protocol: UDP
      targetPort: 53
      name: dns-port
  selector:
    app: pihole
  type: LoadBalancer
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: minio-ingress
  namespace: pihole
spec:
  rules:
    - host: pihole.nickbatson.com
      http:
        paths:
          - path: /
            backend:
              serviceName: pihole-tcp-lb
              servicePort: 8080