---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-volume-claim
  namespace: pihole
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-volume-claim
  namespace: pihole
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi