---
apiVersion: v1
kind: Service
metadata:
  name: minio-lb
  namespace: minio
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      name: web-port
  selector:
    app: minio
  type: LoadBalancer
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: minio-ingress
  namespace: minio
spec:
  rules:
    - host: minio.nickbatson.com
      http:
        paths:
          - path: /
            backend:
              serviceName: minio
              servicePort: 9000